### ISSUE TITLE
examples/fed_issue.rs fails to compile on Windows: cfg(unix)-gated file-mode consts used unconditionally (E0425)

### ISSUE THREAD

**Issue by alphaonedev** [alphaonedev/ai-memory-mcp#1533]
## Defect

`examples/fed_issue.rs` fails to compile on Windows (`Check (windows-latest)` → step `Run tests (impact-aware)`):

```
error[E0425]: cannot find value `PUB_FILE_MODE` in this scope
   --> examples\fed_issue.rs:308:56
error[E0425]: cannot find value `CRED_FILE_MODE` in this scope
   --> examples\fed_issue.rs:339:45
```

## Root cause

`CRED_FILE_MODE` (0o600) and `PUB_FILE_MODE` (0o644) are defined under `#[cfg(unix)]` but passed **unconditionally** to `write_with_mode(path, bytes, mode: u32)` at lines 308/339. `write_with_mode` accepts `mode` on every platform and no-ops it on non-Unix (`#[cfg(not(unix))] { let _ = mode; }`), so the constants must exist on all targets. On Windows the `#[cfg(unix)]` gate configures them out → `E0425`.

The Linux/macOS gate (`cargo test --all-targets`) never caught this because `cfg(unix)` is true there, so the example compiled.

## Evidence

- CI run: PR #1532, `Check (windows-latest)` job 79998821811.
- Pre-existing on `origin/release/v0.7.0` (`06c88c8f`) — not introduced by PR #1532's commits. Last toucher of the file: `cf3e188d` (#1514).

## Fix

Remove `#[cfg(unix)]` from `CRED_FILE_MODE` and `PUB_FILE_MODE` (they're used unconditionally). Keep it on `SECRET_DIR_MODE`, which is referenced only inside a `#[cfg(unix)]` block. Named constants retained — no inlined literals.

Fixed in PR #1532.

**Comment by alphaonedev** [comment]
Fixed and merged to release/v0.7.0 via PR #1532 (merge commit 141621c8).

- `9ff358a2` fix(example): ungated CRED_FILE_MODE/PUB_FILE_MODE so fed_issue compiles on Windows (E0425 resolved).
- `9ee3679f` refactor(federation): extracted testable `resolve_daemon_signing_key`; covers the key-dir-error arm (peer.rs restored above its 91% per-module floor; verified with llvm-cov locally and the Per-Module Coverage gate green on CI).

CI evidence: all 5 platforms (Check windows/macos/ubuntu + Cross-compile ios/android) GREEN, Lint + Per-Module Coverage GREEN on the merged head. Verified per prime directive pm-v3.
