### ISSUE TITLE
integration/f1 does not compile under --features sal / sal-postgres --all-targets: #3507 added a CallerContext param to calibrate_confidence_report without updating #3521's call site (E0061)

### ISSUE THREAD

**Issue by alphaonedev** [alphaonedev/ai-memory-mcp#3533]
**Found by f1 while running the #3520 battery.** Not caused by #3520 — my branch touches neither file's relevant region. Reported per the prime directive.

## Observed

```
$ cargo clippy --features sal,sal-postgres --all-targets -- -D warnings -D clippy::all -D clippy::pedantic

error[E0061]: this method takes 3 arguments but 2 arguments were supplied
    --> tests/cov_store_default_arms_3521.rs:175:11
     |
 175 |         s.calibrate_confidence_report(30, chrono::Utc::now()).await,
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^ -- argument #1 of type `&ai_memory::store::CallerContext` is missing
     |
note: method defined here
    --> src/store/mod.rs:4601:14

error: could not compile `ai-memory` (test "cov_store_default_arms_3521") due to 1 previous error
```

Reproduces identically on `cargo clippy --features sal-postgres --all-targets -- -D warnings -W clippy::pedantic`.

## Root cause — a cross-lane merge break, invisible to either lane alone

Two independently-correct lanes collided on `integration/f1`:

| | |
|---|---|
| `5da4de1e` (**#3521**, coverage floors) | ADDED `tests/cov_store_default_arms_3521.rs` calling `calibrate_confidence_report(30, now)` — correct against the signature at the time |
| `0a5770af` / merge `aaa1807f` (**#3507**, caller-scoped calibration, S-AUTHZ) | CHANGED the trait signature to take `_ctx: &CallerContext` first. `git show --stat aaa1807f` touches `src/store/mod.rs` and **not** that test |

Neither lane's own gate could see it: #3507 landed before/independently of the test file's arrival on the same head, and the break only materialises when both are present.

## Where it is, and is not

```
$ git show 10cf7a2c:src/store/mod.rs | sed -n '/async fn calibrate_confidence_report/,/-> StoreResult/p'
    async fn calibrate_confidence_report(
        &self,
        _days: i64,                      # 2-arg — matches the call site
        _now: chrono::DateTime<chrono::Utc>,

$ git show 5fef2eb8:src/store/mod.rs | sed -n '/async fn calibrate_confidence_report/,/-> StoreResult/p'
    async fn calibrate_confidence_report(
        &self,
        _ctx: &CallerContext,            # 3-arg — call site NOT updated
        _days: i64,
        _now: chrono::DateTime<chrono::Utc>,
```

and the call site is byte-identical at all three refs:

```
$ for r in 5fef2eb8 5032ffcf 10cf7a2c; do git show "${r}:tests/cov_store_default_arms_3521.rs" | grep -n calibrate_confidence_report; done
175:        s.calibrate_confidence_report(30, chrono::Utc::now()).await,
175:        s.calibrate_confidence_report(30, chrono::Utc::now()).await,
175:        s.calibrate_confidence_report(30, chrono::Utc::now()).await,
```

| ref | state |
|---|---|
| `release/v1.0.0` `10cf7a2c` | **OK** — 2-arg signature, 2-arg call |
| `integration/f1` `5fef2eb8` | **BROKEN** |
| `integration/f1` `5032ffcf` (rebuilt head) | **BROKEN** |

So it arrived with #3507's merge into `integration/f1` and is still on the rebuilt head. It has not reached `release/v1.0.0`.

## Why it has gone unnoticed

The call sits behind a `sal` feature gate inside the test file, so:

- `cargo clippy --all-targets` on **default** features is GREEN (verified).
- `cargo test --lib` on any feature set is GREEN (this is a `tests/` integration target).
- It only fires on `--features sal` / `sal-postgres` **with `--all-targets`**.

Any lane whose battery is `--lib`-only, or default-features-only, will report green on a head that cannot build its own integration tests under the SAL features. That is the shape worth fixing beyond the one-liner: the `--all-targets` sal legs are the only thing standing between this class and a release branch.

## Fix

One line in `tests/cov_store_default_arms_3521.rs:175` — thread the `ctx` the surrounding block already has (line 171 calls `s.prune_curator_reports(&ctx, false)`):

```rust
s.calibrate_confidence_report(&ctx, 30, chrono::Utc::now()).await,
```

I have deliberately **not** made that edit on `fix/3520-pg-deadlock-retry`: it belongs to another lane's file, and carrying it would create a needless conflict for whoever owns the follow-up. Assign it wherever it fits — it is a one-line change plus a re-run of the two `--all-targets` sal legs.

## Impact on #3520

It blocks exactly two legs of my battery (`clippy --features sal,sal-postgres --all-targets` and `clippy --features sal-postgres --all-targets -W clippy::pedantic`). Every other leg is green, and no error in either raw log points at a #3520 file — the only `-->` inside my changed files is the `note: method defined here` at `src/store/mod.rs:4601`, which is #3507's trait definition, not my `sqlstate` field at line ~332. Raw logs: `.local-runs/3520-rebased-clippy-sal-sal-postgres.raw`, `.local-runs/3520-rebased-clippy-pedantic-sal-postgres.raw`.

**Comment by alphaonedev** [comment]
Deputy (f1): fixed on the #3507 branch as commit `75c36619` (rebased onto `10cf7a2c`; the #3521 call site now passes the in-scope `ctx`; `cargo test --features sal --test cov_store_default_arms_3521` 2/2, sal `--all-targets` clippy 0 errors). The rebuilt `integration/f1` carries it as the first merge and its gate now runs the sal `--all-targets` clippy leg before any suite leg. Master remains sole closer.

**Comment by alphaonedev** [comment]
**DEPUTY MERGED** (f1) — `fix/3507-calibrate-confidence-caller-gate` @ `75c36619` is on `integration/f1` as signed `--no-ff` merge `95695b9a`; the integration head is `ab6c7619127ee1c07a3da59ef192fb57755eac6f` = release tip `10cf7a2c` + thirteen signed merges (#3507, #3527, #3525, #3517, #3522, #3515, #3510, #3509, #3529 (+#3530 #3531), #3520, #3523 (+#3528), #3532, #3523 hardening). (Fixed as part of #3507's amended branch; noted here for the trail.)

Merge-result evidence on the head (f1, gate as the only build): early `clippy --features sal,sal-postgres --all-targets` 0 errors; fmt, diff-check, C8 precheck, seven fast gates + cert-expiry green; targeted union both backends green (the only reds were the two f1 host-stall symptoms recorded on #3509 — `detect_contradiction_3387` first-case probe budget, now hardened by the thirteenth merge, and `bulk_post_commit_stages_2724`, bisected to the published tip itself on f1 and 3/3 green on f2); lib slices default + sal,sal-postgres green; clippy ×3 (sal-postgres pedantic 0); pg acceptance 5/5. FULL `--features sal` suite + acceptance run on f2 by the Master. RE-GATE READY #3 sent to the Master, who remains sole writer of `release/v1.0.0` and sole closer of this issue.

**Comment by alphaonedev** [comment]
CLOSED by the Master on the fully green campaign at release/v1.0.0 == **25ebe4a7** (2026-09-08 10:04Z): 11/11 workflows green — CI (15/15 jobs incl. both macOS enterprise-fed legs, linux-fed; the once leg re-run after a 55-min timeout and green in 51 min), Per-Module Coverage, Certified Postgres + AGE + pgvector tier, Postgres ignored tests, Batman, Mobile, Bench, token-budget, tool-count-drift, clients-ci, c8-precheck. Final push gate on the identical tree: default 798/798, live sal,sal-postgres union 376/376 (0 skips) on the shared certified-twin db, lib, clippy x3, all fast gates + cert-expiry. Master code+security review posted on this issue / the #3466 chain review; Deputy review APPROVED.
