### ISSUE TITLE
Security: application-level findings requiring remediation

### ISSUE THREAD

**Issue by alphaonedev** [alphaonedev/ai-memory-mcp#173]
## Overview

Full security review identified 9 application-level findings present in both `main` and `develop`. None were introduced by PR #166 — these are pre-existing. Total estimated remediation: ~12-15 hours.

Recommended fix order: top-down by severity. Each finding should be a separate PR.

---

### 1. HTTP API has no authentication + permissive CORS
**Files:** `src/main.rs:548-582`, `src/handlers.rs`
**LOE:** 2-4 hours

`ai-memory serve` binds to localhost:9077 with zero auth and `CorsLayer::permissive()`. Any browser tab on any website can make cross-origin requests to read, modify, or delete all memories. Textbook CSRF/CORS misconfiguration.

**Fix:** Add a `--token` flag or env var to `serve`. Reject requests without `Authorization: Bearer <token>` header. Replace `CorsLayer::permissive()` with `CorsLayer::new()` allowing only configured origins. ~50 lines. Also closes finding #9 (disk fill).

---

### 2. `unsafe impl Send/Sync` on Embedder
**Files:** `src/embeddings.rs:48-49`
**LOE:** 1-2 hours

Unverified safety claim on `BertModel`. `BertModel` from candle does not implement `Send`/`Sync` for a reason. Currently not triggered across threads in production paths, but latent UB if embedding support is added to the HTTP server.

**Fix:** Wrap `BertModel` in `Mutex<BertModel>` instead of `Arc<BertModel>`. Remove the `unsafe impl`. The embedder is only called synchronously, so the mutex is never contended. ~10 lines.

---

### 3. FTS injection via unsanitized `+`/`-` prefix operators
**Files:** `src/db.rs:804-843`
**LOE:** 30 minutes

`sanitize_fts_query` strips `"*^{}():` but not `+`/`-`. In FTS5, `-term` excludes results. A malicious MCP client can send `context: "-important_secret"` to manipulate which memories are returned/excluded from recall.

**Fix:** Add `'+', '-'` to the char filter at `db.rs:821`. Add test cases. One line change.

---

### 4. `memory_forget` bulk delete with no safeguard
**Files:** `src/mcp.rs:960-966`, `src/db.rs:447-481`
**LOE:** 2-3 hours

Single MCP call can wipe all memories in a namespace. No confirmation, no soft-delete, no undo. Combined with no archive-before-forget (archive only applies to GC), a prompt injection attack against the AI client can permanently destroy all stored memories.

**Fix:** Add archive-before-forget (like `gc` already does). Add a `dry_run` parameter. Add a `max_delete` cap (e.g. 1000) requiring explicit `force: true` for larger deletes. ~30 lines.

---

### 5. Consolidation `derived_from` links are CASCADE-deleted
**Files:** `src/db.rs:764-769`
**LOE:** 1-2 hours

Links are created pointing to memory IDs that are immediately deleted in the same transaction. `memory_links` has `ON DELETE CASCADE`, so the `derived_from` links are deleted too. Provenance information is silently lost.

**Fix:** Reorder operations or archive source memories instead of hard deleting. ~20 lines.

---

### 6. HNSW `all_entries` unbounded memory growth
**Files:** `src/hnsw.rs:42-43`
**LOE:** 1-2 hours

Every embedding is kept in-memory forever for rebuilds. ~1.5KB per memory. At 100K memories that's ~150MB just for the shadow copy. No eviction, no cap.

**Fix:** Add a cap to `all_entries` (e.g. 100K). When exceeded, rebuild from DB instead of keeping the shadow copy. ~15 lines.

---

### 7. Raw SQL bypasses `db::update` abstraction
**Files:** `src/mcp.rs:947-953`, `src/mcp.rs:1330`
**LOE:** 30 minutes

`handle_promote` and `auto_register_path_hierarchy` use raw SQL, bypassing tier downgrade protection and collision checks in `db::update`.

**Fix:** Replace raw SQL with calls to `db::update` and extract a `db::set_namespace_parent` function. ~20 lines.

---

### 8. Filesystem path leakage via `auto_register_path_hierarchy`
**Files:** `src/mcp.rs:1305-1343`
**LOE:** 30 minutes

Walks filesystem from cwd upward, writing directory names into the database as namespace parent relationships. Leaks filesystem structure. Behavior depends on what directory the MCP client started the process from — non-deterministic.

**Fix:** Gate behind a config flag `auto_discover_parents = false` (default off), or remove the function. ~5 lines.

---

### 9. ANSI/control char injection in stored content
**Files:** `src/validate.rs:32-34`
**LOE:** 30 minutes

`is_clean_string` only rejects `\0`. All other control characters (backspace, ANSI escape sequences, bidirectional text overrides) are allowed in titles/content and rendered raw in CLI output.

**Fix:** Expand to filter `c.is_control() && c != '\n' && c != '\t'`. One line in `validate.rs`.

---

### 10. 50MB body limit + no auth = disk fill
**Files:** `src/main.rs:580`
**LOE:** N/A — resolved by fix #1 (HTTP auth)

---

## Summary

| Priority | Findings | LOE |
|---|---|---|
| Critical | #1, #2 | ~4-6 hours |
| High | #3, #4 | ~3 hours |
| Medium | #5, #6, #7, #8 | ~3-4 hours |
| Low | #9, #10 | ~30 min |
| **Total** | **9 actionable** | **~12-15 hours** |

## References

- PR #166 — original incident and full review thread
- Issue #170 — governance controls and development procedures

**Comment by alphaonedev** [comment]
## v0.5.4-patch.6 Full Spectrum Test Results

**Binary:** `ai-memory 0.5.4-patch.6` (built from develop @ chore/bump-patch6)
**Automated:** 173 unit + 57 integration = **230 tests, 0 failures**
**cargo audit:** 0 vulnerabilities, 0 warnings
**cargo clippy (pedantic):** clean

### Live Functional Tests

| # | Category | Test | Result |
|---|---|---|---|
| 1 | Store | Short tier with tags | OK |
| 2 | Store | Mid tier with priority | OK |
| 3 | Store | Long tier (no expiry), custom source | OK |
| 4 | Store | Different namespace | OK |
| 5 | Store | High confidence, user source | OK |
| 6 | Recall | Hybrid mode | OK |
| 7 | Recall | Namespace filter | OK |
| 8 | Recall | Tag filter | OK |
| 9 | Search | AND match | OK |
| 10 | Search | No match returns 0 | OK |
| 11 | List | All memories | OK (5) |
| 12 | List | By namespace | OK (3) |
| 13 | List | By tier | OK (3) |
| 14 | Namespaces | List all | OK (3) |
| 15 | Get | By full ID | OK |
| 16 | Update | Content | OK |
| 17 | Update | Priority | OK |
| 18 | Tier protection | Downgrade long→short blocked | OK |
| 19 | Promote | mid→long, clears expiry | OK |
| 20 | Links | related_to | OK |
| 21 | Links | supersedes | OK |
| 22 | Links | Verify count | OK (2) |
| 23 | Dedup | Upsert same title+namespace | OK (same ID) |
| 24 | Consolidate | 2→1 | OK |
| 25 | Resolve | Winner supersedes loser | OK |
| 26 | Forget | MCP dry_run | OK (would_delete=2) |
| 27 | Forget | CLI actual + archive | OK (deleted=2) |
| 28 | Archive | List | OK (2 items) |
| 29 | Archive | Restore | OK |
| 30 | Archive | Purge | OK |
| 31 | Archive | Stats | OK (0 after purge) |
| 32 | GC | Run | OK |
| 33 | Export | Full dump | OK (9 memories, 3 links) |
| 34 | Import | Roundtrip | OK (9 imported, 0 errors) |
| 35 | MCP | initialize | OK (v0.5.4-patch.6, 26 tools) |
| 36 | MCP | tools/list | OK (26) |
| 37 | MCP | prompts/list | OK (2) |
| 38 | MCP | prompts/get recall-first | OK |
| 39 | MCP | prompts/get memory-workflow | OK |
| 40 | MCP | memory_store | OK |
| 41 | MCP | memory_recall | OK |
| 42 | MCP | memory_search | OK |
| 43 | MCP | memory_list | OK |
| 44 | MCP | memory_stats | OK |
| 45 | MCP | memory_capabilities | OK |
| 46 | MCP | memory_gc dry_run | OK |
| 47 | MCP | memory_session_start | OK |
| 48 | Validation | Empty title | Rejected |
| 49 | Validation | Invalid source | Rejected |
| 50 | Validation | Bad priority (99) | Rejected |
| 51 | Validation | Spaces in namespace | Rejected |
| 52 | Validation | Control chars (bell) | Rejected |
| 53 | Completions | bash | OK |
| 54 | Man page | generate | OK |

**53/53 live functional tests pass. 0 regressions.**

**Comment by alphaonedev** [comment]
## Additional Finding: unsafe impl Send/Sync on CrossEncoder

During final security review of develop at v0.5.4-patch.6, found `unsafe impl Send/Sync` on `CrossEncoder` in `src/reranker.rs:50-51`. Same pattern as finding #2 (Embedder). `BertModel` wrapped in `Arc` with unverified unsafe Send/Sync.

**Fix:** PR #185 — wraps `BertModel` in `Mutex`, removes `unsafe impl`. Same approach as PR #179.

### Updated Finding Table

| # | Severity | Finding | Fix | PR | Status |
|---|---|---|---|---|---|
| CVE | Critical | rustls-webpki 0.103.10 | Update to 0.103.12 | #168 | **Merged** |
| 1 | Critical | HTTP API CorsLayer::permissive() | CorsLayer::new() | #175 | **Merged** |
| 2 | Critical | unsafe impl Send/Sync on Embedder | Mutex wrapping | #179 | **Merged** |
| 2b | Critical | unsafe impl Send/Sync on CrossEncoder | Mutex wrapping | #185 | **Open** |
| 3 | High | FTS injection +/- operators | Added to filter | #174 | **Merged** |
| 4 | High | memory_forget no safeguard | Archive + dry_run | #176 | **Merged** |
| 5 | Medium | Consolidation CASCADE deletes links | Metadata provenance | #176 | **Merged** |
| 6 | Medium | HNSW unbounded growth | 100K cap | #178 | **Merged** |
| 7 | Medium | handle_promote raw SQL | db::update | #176 | **Merged** |
| 8 | Medium | Filesystem path leakage | Disabled | #176 | **Merged** |
| 9 | Low | ANSI/control char injection | is_control filter | #177 | **Merged** |
| 10 | Low | 50MB body + no auth | 2MB + API key auth | — | **Already on develop** |

### Final Codebase Audit (post all fixes)

- `cargo audit`: 0 vulnerabilities, 0 warnings
- `cargo clippy --pedantic`: clean
- `cargo fmt --check`: clean
- 173 unit + 57 integration = 230 tests, 0 failures
- `unsafe impl` in codebase: **0** (after PR #185)
- `unsafe` blocks: 2 (candle mmap — required by library, no safe alternative)

**Comment by alphaonedev** [comment]
Closing — v0.6.0 GA shipped 2026-04-19 with comprehensive security hardening landing across #271 (SQLCipher), #272 (webhook SSRF-hardened), #295/#296/#297/#298 (SAL security blockers), #231/#232/#237/#240/#241/#243 (red-team P1/P2/P3 triage). The meta-tracker has served its purpose. Any new security findings should be filed as specific issues against v0.6.x or later. See `docs/SECURITY.md` for current posture.
